# Generated by Django 3.2.18 on 2023-07-17 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zohoapp', '0002_auto_20230715_0626'),
    ]

    operations = [
        migrations.AddField(
            model_name='chart_of_account',
            name='create_status',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
