# Generated by Django 3.2.18 on 2023-07-19 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zohoapp', '0003_chart_of_account_create_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchase_order_items',
            name='tax',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
