# Generated by Django 3.2.18 on 2023-07-21 07:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zohoapp', '0004_alter_purchase_order_items_tax'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchase',
            name='Account_type',
            field=models.CharField(choices=[('1', 'EXPENSE'), ('2', 'Cost of Goods Sold'), ('3', 'Fixed Asset')], max_length=255),
        ),
    ]
