# Generated by Django 3.2.18 on 2023-07-22 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zohoapp', '0006_retainerinvoice_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='expense',
            name='activation_tag',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='expense',
            name='comments',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='expense',
            name='document',
            field=models.FileField(blank=True, null=True, upload_to='uploads/'),
        ),
        migrations.AddField(
            model_name='expense',
            name='status',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='expense',
            name='title',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='expense',
            name='ends_on',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
