# Generated by Django 3.2.18 on 2023-08-07 08:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('zohoapp', '0013_accounte_addcustomere_attache_expensee_vendor_tablee'),
    ]

    operations = [
        migrations.RenameField(
            model_name='payroll',
            old_name='name',
            new_name='first_name',
        ),
        migrations.RemoveField(
            model_name='payroll',
            name='attachment',
        ),
        migrations.AddField(
            model_name='payroll',
            name='emergency_phone',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='payroll',
            name='last_name',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='payroll',
            name='permanent_address',
            field=models.CharField(max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='payroll',
            name='title',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='payroll',
            name='emp_number',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.CreateModel(
            name='Payrollfiles',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attachment', models.FileField(null=True, upload_to='doc/')),
                ('payroll', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='zohoapp.payroll')),
            ],
        ),
    ]
