# Generated by Django 3.2.18 on 2023-08-08 07:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zohoapp', '0014_auto_20230807_0806'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='active',
            field=models.CharField(default='Active', max_length=255),
        ),
        migrations.AlterField(
            model_name='project1',
            name='active',
            field=models.BooleanField(default=True),
        ),
        migrations.DeleteModel(
            name='usernamez',
        ),
    ]
