# Generated by Django 3.2.18 on 2023-08-08 07:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('zohoapp', '0015_auto_20230808_0702'),
    ]

    operations = [
        migrations.CreateModel(
            name='usernamez',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('usernamez', models.CharField(blank=True, max_length=255, null=True)),
                ('emailz', models.CharField(blank=True, max_length=255, null=True)),
                ('projn', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='zohoapp.project1')),
                ('users', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
