# Generated by Django 3.2.18 on 2023-08-09 08:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zohoapp', '0016_usernamez'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bankdetails',
            name='acc_no',
            field=models.BigIntegerField(),
        ),
        migrations.AlterField(
            model_name='payroll',
            name='Phone',
            field=models.BigIntegerField(),
        ),
        migrations.AlterField(
            model_name='payroll',
            name='emergency_phone',
            field=models.BigIntegerField(null=True),
        ),
    ]
