# Generated by Django 3.2.18 on 2023-08-11 07:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zohoapp', '0019_credits_comments_table_credits_doc_upload_table_credits_mail_table_vendor_credits_vendor_invoice_ite'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payroll',
            name='Aadhar',
            field=models.CharField(default='', max_length=250),
        ),
        migrations.AlterField(
            model_name='payroll',
            name='emergency_phone',
            field=models.BigIntegerField(blank=True, default=1, null=True),
        ),
    ]
