# Generated by Django 3.2.18 on 2023-08-17 08:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('zohoapp', '0022_auto_20230817_0450'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customer',
            old_name='CPdepartment',
            new_name='pan_no',
        ),
        migrations.RenameField(
            model_name='customer',
            old_name='CPdesignation',
            new_name='remark',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='CPemail',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='CPmobile',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='CPphone',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='CPsalutation',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='CPskype',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='Firstname',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='Lastname',
        ),
        migrations.CreateModel(
            name='customer_contact_person_table',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('CPsalutation', models.CharField(blank=True, max_length=100, null=True)),
                ('Firstname', models.CharField(blank=True, max_length=100, null=True)),
                ('Lastname', models.CharField(blank=True, max_length=100, null=True)),
                ('CPemail', models.CharField(blank=True, max_length=100, null=True)),
                ('CPphone', models.CharField(blank=True, max_length=100, null=True)),
                ('CPmobile', models.CharField(blank=True, max_length=100, null=True)),
                ('CPskype', models.CharField(blank=True, max_length=100, null=True)),
                ('CPdesignation', models.CharField(blank=True, max_length=100, null=True)),
                ('CPdepartment', models.CharField(blank=True, max_length=100, null=True)),
                ('Customr', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='zohoapp.customer')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
