# Generated by Django 3.2.18 on 2023-08-22 08:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zohoapp', '0025_customer_comments_table_customer_doc_upload_table_customer_mail_table'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchasebills',
            name='vendor_gst_no',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
