# Generated by Django 3.2.18 on 2023-08-22 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zohoapp', '0026_purchasebills_vendor_gst_no'),
    ]

    operations = [
        migrations.RenameField(
            model_name='salesorder',
            old_name='d_method',
            new_name='sos',
        ),
        migrations.RemoveField(
            model_name='salesorder',
            name='s_person',
        ),
        migrations.AddField(
            model_name='salesorder',
            name='sh_charge',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
